Repository Maliz30/Interpretador_Cpp-Py, pull requests merged in 2025-04, with the labels that each got.

#1 FIxing sprint template and starting lexer code
  mkdocs/docs/sprints/sprint-1/sprint-planning.md
  mkdocs/docs/sprints/sprint-1/sprint-review.md
  mkdocs/docs/sprints/template.md
  src/lexer/lexer.l
  src/parser/parser.y
Labels: documentation, code

#2 docs: Adição do cronograma
  mkdocs/docs/index.md
  mkdocs/docs/organizacao-planejamento/boas-praticas.md
  mkdocs/docs/organizacao-planejamento/planejamento.md
  mkdocs/docs/sprints/planejamento.md
  mkdocs/mkdocs.yml
Labels: documentation

#8 Creation of first sprint planning documentation
  mkdocs/docs/sprints/sprint-1/sprint-planning.md
Labels: documentation

#15 Adiciona arquivo léxico com tokens
  src/lexer/lexer.l
  src/teste.txt
Labels: code

#16 docs: Adiciona a review da sprint 1
  mkdocs/docs/sprints/sprint-1/sprint-review.md
Labels: documentation

#22 Adicionando loop e condicionais
  src/codigos_teste/conditional.cpp
  src/codigos_teste/loop.cpp
  src/executavel
  src/lexer/lex.yy.c
  src/parser/parser.tab.c
  src/parser/parser.tab.h
  src/parser/parser.y
Labels: code
